# Generated by Django 5.0.3 on 2024-04-01 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='license_plate',
            new_name='licence_plate',
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 19, 22, 26, 374452)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_term',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 20, 22, 26, 374452)),
        ),
    ]
